In [1]:
import numpy as np

In [2]:
def create_polynomial_features(X, degree=2):
    """
    Creates the polynomial features
    Args:
        X: A array tensor for the data.
        degree: An integer for the degree of the polynomial.
    """
    X_new = X
    for d in range(2, degree + 1):
        X_new = np.c_[X_new, np.power(X, d)]

    return X

In [12]:
def create_polynomial_features(X, degree=2):
    """
    Creates the polynomial features
    Args:
        X: A array tensor for the data.
        degree: An integer for the degree of the polynomial.
    """

    X_mem = []
    for X_sub in X.T:
        X_sub = X_sub.T
        X_new = X_sub
        for d in range(2, degree + 1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

In [13]:
X = np.array([[1, 2], [2, 3], [3, 4]])
print(create_polynomial_features(X, 2))

[[ 1  1  2  4]
 [ 2  4  3  9]
 [ 3  9  4 16]]
