In [3]:
import numpy as np

In [4]:
# Câu hỏi 1: Câu nào sau đây là đúng để tạo mảng 1 chiều từ 0 đến 9

In [5]:
arr = np.arange (0 , 10 , 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr = np.arange (1 , 10 , 1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr = np.arange (0 , 9 , 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
arr = np.arange (1 , 11 , 1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# -> a)

In [11]:
# Câu hỏi 2: Cách tạo một mảng boolean 3x3 với tất cả giá trị là True

In [12]:
arr = np.ones ((3 ,3) ) > 0
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
arr = np.ones ((3 ,3), dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [14]:
arr = np.full((3 ,3), fill_value=True, dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
# -> d)

In [16]:
# Câu hỏi 3: Kết quả của đoạn code sau đây:

In [18]:
arr = np.arange (0 ,10)
print(arr[arr%2 == 1])

[1 3 5 7 9]


In [19]:
# -> a)

In [20]:
# Câu hỏi 4: Kết quả của đoạn code sau đây:

In [21]:
arr = np.arange(0,10)
arr[arr%2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [22]:
# -> b)

In [23]:
# Câu hỏi 5: Kết quả của đoạn code sau đây:

In [24]:
arr = np.arange(10)
arr_2d = arr.reshape(2,-1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
# -> b

In [26]:
# Câu hỏi 6: Kết quả của đoạn code sau đây:

In [27]:
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)
c = np.concatenate([arr1,arr2],axis=0)
print("Result:\n",c)

Result:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [28]:
# -> a)

In [29]:
# Câu hỏi 7: Kết quả của đoạn code sau đây:

In [30]:
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)
c = np.concatenate([arr1,arr2], axis=1)
print("C = ",c)

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [31]:
# -> c)

In [32]:
# Câu hỏi 8: Kết quả của đoạn code sau đây:

In [33]:
arr = np.array([1,2,3])
print(np.repeat(arr,3))
print(np.tile(arr,3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [34]:
# -> a)

In [35]:
# Câu hỏi 9: Kết quả của đoạn code sau đây:

In [36]:
a = np.array([2,6,1,9,10,3,27])
index = np.where((a>=5)&(a<=10))
print("result",a[index])

result [ 6  9 10]


In [37]:
# -> c)

In [38]:
# Câu hỏi 10: Kết quả của đoạn code sau đây:

In [39]:
def maxx(x, y):
    if x >= y :
        return x
    else :
        return y

a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])
pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a,b))

[6. 7. 9. 8. 9. 7. 5.]


In [40]:
# -> d)

In [41]:
# Câu hỏi 11: Kết quả của đoạn code sau đây:

In [42]:
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])
print("Result", np.where(a<b,b,a))

Result [6 7 9 8 9 7 5]


In [ ]:
# -> a)